Importing the Dependecies

In [ ]:
#Workflow Of Sci-Kit Learn
'''
1) Setting up the data
2) Creating the Model
3) Training the Model
4) Prediction
'''

'\n1) Setting up the data\n2) Creating the Model\n3) Training the Model\n4) Prediction\n'

In [ ]:
#Importing important libraries
import numpy as np
import pandas as pd

In [ ]:
#Importing LinearRegression Model
from sklearn.linear_model import LinearRegression

In [ ]:
#Importing accuracy score function
from sklearn import metrics

In [ ]:
from sklearn.model_selection import train_test_split

Data Collection and Analysis

In [ ]:
car_dataset = pd.read_csv('car data.csv')

In [ ]:
#Displaying first 5 rows
car_dataset.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [ ]:
#Finding no. of rows and columns
car_dataset.shape

(301, 9)

In [ ]:
#Info of the dataset
car_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

In [ ]:
#Finding the sum of null values
car_dataset.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [ ]:
#Checking the distribution of categorical data
#car_dataset['Fuel_Type'].unique()
pd.unique(car_dataset['Fuel_Type'])
car_dataset['Fuel_Type'].value_counts()

Petrol    239
Diesel     60
CNG         2
Name: Fuel_Type, dtype: int64

In [ ]:
#Transmission
pd.unique(car_dataset['Transmission'])
car_dataset['Transmission'].value_counts()

Manual       261
Automatic     40
Name: Transmission, dtype: int64

In [ ]:
#Seller Type
pd.unique(car_dataset['Seller_Type'])
car_dataset['Seller_Type'].value_counts()

Dealer        195
Individual    106
Name: Seller_Type, dtype: int64

Encoding the Categorical Data

In [ ]:
#Encoding the Fuel_Type column
car_dataset.replace({'Fuel_Type':{'Petrol':0, 'Diesel':1, 'CNG':2}}, inplace = True)
#Petrol - 0
#Diesel - 1
#CNG - 2

#Encoding the Transmission Column
car_dataset.replace({'Transmission':{'Manual':0, 'Automatic':1}}, inplace = True)
#Manual - 0
#Automatic - 1

#Encoding the Seller_Type Column
car_dataset.replace({'Seller_Type':{'Dealer':0, 'Individual':1}}, inplace = True)
#Dealer - 0
#Individual - 1

In [ ]:
car_dataset

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,0,0,0,0
1,sx4,2013,4.75,9.54,43000,1,0,0,0
2,ciaz,2017,7.25,9.85,6900,0,0,0,0
3,wagon r,2011,2.85,4.15,5200,0,0,0,0
4,swift,2014,4.60,6.87,42450,1,0,0,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,1,0,0,0
297,brio,2015,4.00,5.90,60000,0,0,0,0
298,city,2009,3.35,11.00,87934,0,0,0,0
299,city,2017,11.50,12.50,9000,1,0,0,0
300,brio,2016,5.30,5.90,5464,0,0,0,0

Splitting the data into Training Data and Testing Data

In [ ]:
X = car_dataset.drop(['Car_Name', 'Selling_Price'], axis = 1)
Y = car_dataset['Selling_Price']

In [ ]:
#Splitting the data into training data and testing data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 2)

In [ ]:
print(X.shape, X_train.shape, Y_test.shape)

(301, 7) (240, 7) (61,)

Model Training

In [ ]:
#Calling Linear Regression Model
model = LinearRegression()

In [ ]:
#Training the ML Model using training data
model.fit(X_train, Y_train)

LinearRegression()

In [ ]:
training_data_prediction = model.predict(X_train)

In [ ]:
'''
training_data_accuracy = accuracy_score(Y_train, X_train_prediction)
print("Accuracy Score of training data", training_data_accuracy)
'''
training_data_accuracy = metrics.r2_score(Y_train, training_data_prediction)
print("Accuracy Score of training data", training_data_accuracy)

Accuracy Score of training data 0.8838169193709796

In [ ]:
testing_data_prediction = model.predict(X_test)

In [ ]:
testing_data_accuracy = metrics.r2_score(Y_test, testing_data_prediction)
print("Accuracy Score of training data", testing_data_accuracy)

Accuracy Score of training data 0.8401532365377697

Building a Predictive System

In [ ]:
input_data = (2010,7.98,41442,0,0,0,0)

input_data_as_numpy_array = np.array(input_data)
#Reshape the numpy array as we are predicting for one data point
input_data_reshape = input_data_as_numpy_array.reshape(1,-1)

In [ ]:
prediction = model.predict(input_data_reshape)
print('Car price according to the prediction:', prediction)

Car price according to the prediction: [3.14891182]

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(